apiVersion: apps/v1
kind: Deployment
metadata:
  name: pro-server
  labels:
    app: pro-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pro-server
  template:
    metadata:
      labels:
        app: pro-server
    spec:
      containers:
        - name: pro-server
          image: alielhabal70/final-pro:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources: {}
    
---
apiVersion: v1
kind: Service
metadata:
  name: pro-service
spec:
  selector:
    app: pro-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort

