apiVersion: apps/v1
kind: Deployment
metadata:
  name: final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pro-server
    spec:
      containers:
        - name: pro-server
          image:  ali3elhabal/final-pro:latest
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 8080
    
 


